# Top Earners in Movie Industry

## Table of Contents

<ul>
    <li><a href="#intro">Introduction</a></li>
    <li><a href="#eda">Exploratory Data Analysis</a></li>
    <li><a href="#conclusion">Conclusion</a></li>
</ul>

<a id="#intro"></a>
## Introduction

> This analysis project is to be done using the imdb movie data. When the analysis is completed, you should be able to find the top 5 highest grossing directors, the top 5 highest grossing movie genres of all time, comparing the revenue of the highest grossing movies and which companies released the most movies. 

> There are 10 columns that will not be needed for the analysis. Use pandas to drop these columns. HINT: Only the columns pertaining to revenue will be needed.

> To get you started, I've already placed the needed code for getting the packages and datafile that you will be using for the project.

In [1]:
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('imdb-movies.csv')

### Drop columns without neccesary information and remove all records with no financial information -- Pay close attention to things that don't tell you anything regarding financial data

In [4]:
imdb = df.copy(deep = True)
imdb

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/15,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/15,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/15,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/15,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/15,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95,Documentary,Bruce Brown Films,6/15/66,11,7.4,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/66,20,5.7,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94,Mystery|Comedy,Mosfilm,1/1/66,11,6.5,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,NaN,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80,Action|Comedy,Benedict Pictures Corp.,11/2/66,22,5.4,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74,Horror,Norm-Iris,11/15/66,15,1.5,1966,1.276423e+05,0.000000e+00

In [5]:
imdb.drop(['cast', 'homepage', 'tagline', 'keywords', 'overview', 'runtime', 'release_date', 'vote_count', 'vote_average'], axis=1, inplace=True)
imdb.head()

,id,imdb_id,popularity,budget,revenue,original_title,director,genres,production_companies,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Colin Trevorrow,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,George Miller,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Robert Schwentke,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,J.J. Abrams,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,James Wan,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015,1.747999e+08,1.385749e+09

In [7]:
# drop popularity column
imdb.drop('popularity', axis=1, inplace=True)

KeyError: "['popularity'] not found in axis"

### Data Cleaning

In [8]:
# Delete all records with null, or empty values

new_data = imdb.dropna()

# Confirm: Old number of rows 10866. New number of rows 9805
new_data

,id,imdb_id,budget,revenue,original_title,director,genres,production_companies,release_year,budget_adj,revenue_adj
0,135397,tt0369610,150000000,1513528810,Jurassic World,Colin Trevorrow,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,150000000,378436354,Mad Max: Fury Road,George Miller,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,110000000,295238201,Insurgent,Robert Schwentke,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,J.J. Abrams,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,190000000,1506249360,Furious 7,James Wan,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0,0,The Endless Summer,Bruce Brown,Documentary,Bruce Brown Films,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0,0,Grand Prix,John Frankenheimer,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0,0,Beregis Avtomobilya,Eldar Ryazanov,Mystery|Comedy,Mosfilm,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0,0,"What's Up, Tiger Lily?",Woody Allen,Action|Comedy,Benedict Pictures Corp.,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,19000,0,Manos: The Hands of Fate,Harold P. Warren,Horror,Norm-Iris,1966,1.276423e+05,0.000000e+00

#### Here's a helpful hint from my own analysis when I ran this the first time. This may help shed light on what your data set should look like.

#### If I created one record for each the `production_companies` a movie was release under and one record each for `genres`<br>and tried to run calculations, it wouldn't work because for many records, the amount of `production_companies`<br>and `genres` aren't the same, so I'll create 2 dataframes; one w/o a `production_companies` column and one w/o a `genres` columns

In [10]:
# delete genres column
no_genre_col = new_data.copy(deep = True)

no_genre_col.drop('genres', axis=1, inplace=True)

no_genre_col

,id,imdb_id,budget,revenue,original_title,director,production_companies,release_year,budget_adj,revenue_adj
0,135397,tt0369610,150000000,1513528810,Jurassic World,Colin Trevorrow,Universal Studios|Amblin Entertainment|Legenda...,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,150000000,378436354,Mad Max: Fury Road,George Miller,Village Roadshow Pictures|Kennedy Miller Produ...,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,110000000,295238201,Insurgent,Robert Schwentke,Summit Entertainment|Mandeville Films|Red Wago...,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,J.J. Abrams,Lucasfilm|Truenorth Productions|Bad Robot,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,190000000,1506249360,Furious 7,James Wan,Universal Pictures|Original Film|Media Rights ...,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0,0,The Endless Summer,Bruce Brown,Bruce Brown Films,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0,0,Grand Prix,John Frankenheimer,Cherokee Productions|Joel Productions|Douglas ...,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0,0,Beregis Avtomobilya,Eldar Ryazanov,Mosfilm,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0,0,"What's Up, Tiger Lily?",Woody Allen,Benedict Pictures Corp.,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,19000,0,Manos: The Hands of Fate,Harold P. Warren,Norm-Iris,1966,1.276423e+05,0.000000e+00

In [9]:
# delete production_companies column
no_prod_comp = new_data.copy(deep = True)

no_prod_comp.drop('production_companies', axis=1, inplace=True)

no_prod_comp

,id,imdb_id,budget,revenue,original_title,director,genres,release_year,budget_adj,revenue_adj
0,135397,tt0369610,150000000,1513528810,Jurassic World,Colin Trevorrow,Action|Adventure|Science Fiction|Thriller,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,150000000,378436354,Mad Max: Fury Road,George Miller,Action|Adventure|Science Fiction|Thriller,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,110000000,295238201,Insurgent,Robert Schwentke,Adventure|Science Fiction|Thriller,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,J.J. Abrams,Action|Adventure|Science Fiction|Fantasy,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,190000000,1506249360,Furious 7,James Wan,Action|Crime|Thriller,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...
10861,21,tt0060371,0,0,The Endless Summer,Bruce Brown,Documentary,1966,0.000000e+00,0.000000e+00
10862,20379,tt0060472,0,0,Grand Prix,John Frankenheimer,Action|Adventure|Drama,1966,0.000000e+00,0.000000e+00
10863,39768,tt0060161,0,0,Beregis Avtomobilya,Eldar Ryazanov,Mystery|Comedy,1966,0.000000e+00,0.000000e+00
10864,21449,tt0061177,0,0,"What's Up, Tiger Lily?",Woody Allen,Action|Comedy,1966,0.000000e+00,0.000000e+00
10865,22293,tt0060666,19000,0,Manos: The Hands of Fate,Harold P. Warren,Horror,1966,1.276423e+05,0.000000e+00

<a id="eda"></a>
## Exploratory Data Analysis

> Use Matplotlib to display your data analysis

### Which production companies released the most movies in the last 10 years? Display the top 5 production companies.

In [11]:
#  movies released within the last 10 years 
no_genre_col['movie_count'] = 2021 - no_genre_col['release_year'] <=10
no_genre_col.sort_values('movie_count', ascending = False).head()

no_genre_col['count'] = 1

# top production
ten_yrs = pd.DataFrame(no_genre_col[(no_genre_col['movie_count'] == True)].groupby('production_companies').sum()['count'])


print(f" in the last 10 years most movies was released by Asylum production :")

ten_yrs.sort_values('count', ascending=False).head()

 in the last 10 years most movies was released by Asylum production :

                         count
production_companies
The Asylum                  18
Marvel Studios              14
Pixar Animation Studios     12
DreamWorks Animation        11
WWE Studios                 10

### What 5 movie genres grossed the highest all-time?

In [12]:
no_prod_comp['high_grossing_genres'] = no_prod_comp['revenue_adj'] - no_prod_comp['budget_adj']
print(no_prod_comp.groupby('genres').sum()[['high_grossing_genres']].sort_values('high_grossing_genres', ascending = False).head())


print('\n')

                                  high_grossing_genres
genres
Comedy                                    1.719016e+10
Drama                                     1.379119e+10
Comedy|Romance                            1.045779e+10
Adventure|Action|Thriller                 9.070750e+09
Adventure|Action|Science Fiction          8.365912e+09

### Who are the top 5 grossing directors?

### Compare the revenue of the highest grossing movies of all time.

In [13]:
print(f" Top 5 Highest Grossing Movies of All-Time : \n")

no_genre_col['high_grossing_movies'] = no_genre_col['revenue_adj'] - no_genre_col['budget_adj']
print(no_genre_col[['id','original_title','high_grossing_movies']].sort_values('high_grossing_movies', ascending=False).head())

print('\n')

 Top 5 Highest Grossing Movies of All-Time :

          id original_title  high_grossing_movies
1329      11      Star Wars          2.750137e+09
1386   19995         Avatar          2.586237e+09
5231     597        Titanic          2.234714e+09
10594   9552   The Exorcist          2.128036e+09
9806     578           Jaws          1.878643e+09

<a id="conclusions"></a>
## Conclusions

> Using the cell below, write a brief conclusion of what you have found from the anaylsis of the data. The Cell below will allow you to write plan text instead of code.